"""

Revision ID: 35cb81e4eb75
Revises: e2b3a3abf398
Create Date: 2018-01-10 21:38:08.994426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cb81e4eb75'
down_revision = 'e2b3a3abf398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('dob', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'dob')
    # ### end Alembic commands ###
