"""'initialize'

Revision ID: 36f37f87cd1c
Revises: 980a7170177c
Create Date: 2018-01-06 01:35:32.573883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f37f87cd1c'
down_revision = '980a7170177c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=False),
    sa.Column('prior', sa.String(length=15), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Float(), nullable=False),
    sa.Column('rpg', sa.Float(), nullable=False),
    sa.Column('apg', sa.Float(), nullable=False),
    sa.Column('pie', sa.Float(), nullable=False),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('playerstats')
    op.drop_table('playerprofile')
    # ### end Alembic commands ###
