"""empty message

Revision ID: 4a03420c6e09
Revises: bd3b8e0d2a86
Create Date: 2018-01-21 21:29:54.782439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a03420c6e09'
down_revision = 'bd3b8e0d2a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastgamestats', sa.Column('fouls', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lastgamestats', 'minutes')
    op.drop_column('lastgamestats', 'fouls')
    # ### end Alembic commands ###
