"""

Revision ID: 4ad400628f65
Revises: 35cb81e4eb75
Create Date: 2018-01-10 21:53:11.313847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad400628f65'
down_revision = '35cb81e4eb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playerstats', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playerstats', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
