"""

Revision ID: 504d95c549e9
Revises: db4e298844cf
Create Date: 2018-01-10 21:14:14.070821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504d95c549e9'
down_revision = 'db4e298844cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('dob', sa.Integer(), nullable=False))
    op.drop_column('playerprofile', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('playerprofile', 'dob')
    # ### end Alembic commands ###
