"""

Revision ID: 74450004b08d
Revises: 368399398a80
Create Date: 2018-01-10 21:05:42.883041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74450004b08d'
down_revision = '368399398a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('position', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'position')
    # ### end Alembic commands ###
