"""

Revision ID: 8020a4c47e80
Revises: 35cb81e4eb75
Create Date: 2018-01-11 19:51:43.320143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8020a4c47e80'
down_revision = '35cb81e4eb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('pid', sa.Integer(), nullable=True))
    op.alter_column('playerprofile', 'dob',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('playerstats', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playerstats', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerprofile', 'dob',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('playerprofile', 'pid')
    # ### end Alembic commands ###
