"""added columns

Revision ID: 8a291a3408b5
Revises: c2d73de82c2d
Create Date: 2018-01-10 20:07:53.050964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a291a3408b5'
down_revision = 'c2d73de82c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=False),
    sa.Column('prior', sa.String(length=15), nullable=False),
    sa.Column('team', sa.String(length=15), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Float(), nullable=False),
    sa.Column('rpg', sa.Float(), nullable=False),
    sa.Column('apg', sa.Float(), nullable=False),
    sa.Column('pie', sa.Float(), nullable=False),
    sa.Column('bpg', sa.Float(), nullable=True),
    sa.Column('spg', sa.Float(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['playerprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerstats')
    op.drop_table('playerprofile')
    op.drop_table('users')
    # ### end Alembic commands ###
