"""

Revision ID: 8e226fdb09c8
Revises: 74450004b08d
Create Date: 2018-01-10 21:10:30.266617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e226fdb09c8'
down_revision = '74450004b08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('picture', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
