"""empty message

Revision ID: bd3b8e0d2a86
Revises: dbd2d0526537
Create Date: 2018-01-21 20:35:37.318764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3b8e0d2a86'
down_revision = 'dbd2d0526537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lastgamestats', sa.Column('defensive_rebounds', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('field_goals_attempted', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('field_goals_made', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('free_throw_percentage', sa.Float(), nullable=True))
    op.add_column('lastgamestats', sa.Column('free_throws_attempted', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('free_throws_made', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('offensive_rebounds', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('result', sa.String(length=2), nullable=True))
    op.add_column('lastgamestats', sa.Column('three_point_field_goal_percentage', sa.Float(), nullable=True))
    op.add_column('lastgamestats', sa.Column('three_pointers_attempted', sa.Integer(), nullable=True))
    op.add_column('lastgamestats', sa.Column('three_pointers_made', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lastgamestats', 'three_pointers_made')
    op.drop_column('lastgamestats', 'three_pointers_attempted')
    op.drop_column('lastgamestats', 'three_point_field_goal_percentage')
    op.drop_column('lastgamestats', 'result')
    op.drop_column('lastgamestats', 'offensive_rebounds')
    op.drop_column('lastgamestats', 'free_throws_made')
    op.drop_column('lastgamestats', 'free_throws_attempted')
    op.drop_column('lastgamestats', 'free_throw_percentage')
    op.drop_column('lastgamestats', 'field_goals_made')
    op.drop_column('lastgamestats', 'field_goals_attempted')
    op.drop_column('lastgamestats', 'defensive_rebounds')
    # ### end Alembic commands ###
