"""per column added

Revision ID: bf7b326e31cc
Revises: 8a291a3408b5
Create Date: 2018-01-10 20:35:28.732442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7b326e31cc'
down_revision = '8a291a3408b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstats', sa.Column('per', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerstats', 'per')
    # ### end Alembic commands ###
