"""player profile picture column added

Revision ID: d5c29b2292ea
Revises: 4bb77b1a0af6
Create Date: 2018-01-06 03:58:13.202292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c29b2292ea'
down_revision = '4bb77b1a0af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('picture', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'picture')
    # ### end Alembic commands ###
