"""

Revision ID: db4e298844cf
Revises: 8e226fdb09c8
Create Date: 2018-01-10 21:10:50.712931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4e298844cf'
down_revision = '8e226fdb09c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('picture', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'picture')
    # ### end Alembic commands ###
