"""

Revision ID: e2b3a3abf398
Revises: 504d95c549e9
Create Date: 2018-01-10 21:37:52.705322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b3a3abf398'
down_revision = '504d95c549e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('dob', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
