"""empty message

Revision ID: eb083f9e5bfc
Revises: 4a03420c6e09
Create Date: 2018-01-21 22:10:58.218190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb083f9e5bfc'
down_revision = '4a03420c6e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprofile', 'prior')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprofile', sa.Column('prior', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
